app:
  name: jenkins
  image:
    name: jenkins/jenkins
    tag: lts
  namespace: devops-tools
  replicas: 1

  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "500Mi"
      cpu: "500m"

  service:
    port: 8080
    targetPort: 8080
    nodePort: 32000