controller:
  name: jenkins
  image: jenkins/jenkins
  tag: jenkins:2.60.3
  namespace: devops-tools
  replicas: 1
  ports:
    httpPort: 8080
    jnlpPort: 5000

  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "500Mi"
      cpu: "500m"

  agentListenerPort: 8080


autoscaling:
  enabled: false

ingress:
  enabled: false

nodes:
  node1: k8sworker1-virtual-machine
  node2: k8sworker2-virtual-machine

createServiceAccount:
  enabled: true

createClusterRoleBinding:
  enabled: true

createClusterRole:
  enabled: true