apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name}}
  namespace: {{ .Values.controller.namespace}}
spec:
  replicas: {{ .Values.controller.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.controller.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.name}}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: {{ .Values.controller.name}}
          image: {{ .Values.controller.image}}:{{ .Values.controller.tag}}
          resources:
            limits:
              memory: {{ .Values.controller.resources.limits.memory}}
              cpu: {{ .Values.controller.resources.limits.cpu}}
            requests:
              memory: {{ .Values.controller.resources.requests.memory}}
              cpu: {{ .Values.controller.resources.requests.cpu}}
          ports:
            - name: httpport
              containerPort: {{ .Values.controller.ports.httpPort | default "8080"}}
            - name: jnlpport
              containerPort: {{ .Values.controller.ports.jnlpPort | default "5000"}}
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/tmp/config
            - name: jenkins-env-vars
              mountPath: /vars/tmp/config/env_vars

      volumes:
        - name: jenkins-config
          configMap:
            name: jcasc-configmap
        - name: jenkins-env-vars
          configMap:
            name: jenkins-env-vars
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Values.controller.name}}-pv-claim





