apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Values.controller.name}}-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: {{ .Values.controller.name}}-pv-claim
    namespace: {{ .Values.controller.namespace}}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodes.node1}}