#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ .Values.controller.name}}-service
#  namespace: {{ .Values.controller.namespace}}
#  annotations:
#    prometheus.io/scrape: 'true'
#    prometheus.io/path:   /
#    prometheus.io/port:   '8080'
#spec:
#  selector:
#    app: {{ .Values.controller.name}}
#  type: NodePort
#  ports:
#    - port: {{ .Values.controller.agentListenerPort}}
#      targetPort:  {{ .Values.controller.agentListenerPort}}
#      nodePort:  {{ .Values.controller.nodePort}}
#
#
#
#
#
#
#

