{{- if .Values.createServiceAccount.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}-admin
  namespace: {{ .Values.controller.namespace}}
{{- end}}
---
{{- if .Values.createClusterRole.enabled}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.controller.name }}-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
{{- end}}
---
{{- if .Values.createClusterRoleBinding.enabled}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.controller.name }}-clusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Values.controller.name }}-admin
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.controller.name }}-admin
    namespace: {{ .Values.controller.namespace}}
{{- end}}
---

