apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.controller.name}}-virtual-service
  namespace: {{ .Values.controller.namespace}}
spec:
  hosts:
  - "jenkins.sujangcloud.com"
  gateways:
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /

    route:
    - destination:
        host: {{ .Values.controller.name}}-service.devops-tools.svc.cluster.local
        port:
          number:  {{ .Values.controller.agentListenerPort}}




